"""Generate Unity/Assets/TacSim/Scripts/Tac/ArucoOriginal.cs from OpenCV's DICT_ARUCO_ORIGINAL.

TAC Challenge uses the "Original ArUco" dictionary. Run from the repository root:
    cd automation-demo && uv run python ../scripts/gen_aruco_table.py
"""

from pathlib import Path

import cv2

OUT = Path(__file__).resolve().parents[1] / "Unity/Assets/TacSim/Scripts/Tac/ArucoOriginal.cs"

dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_ARUCO_ORIGINAL)
codes = []
for marker_id in range(dictionary.bytesList.shape[0]):
    # 5x5 data cells inside a one-cell black border; bit 24 is the top-left cell, row-major.
    cells = cv2.aruco.generateImageMarker(dictionary, marker_id, 7)[1:6, 1:6] // 255
    code = 0
    for value in cells.flatten():
        code = (code << 1) | int(value)
    codes.append(code)

rows = ",\n".join(
    "            " + ", ".join(f"0x{code:07X}" for code in codes[i:i + 8]) for i in range(0, len(codes), 8)
)
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Generated by scripts/gen_aruco_table.py from OpenCV DICT_ARUCO_ORIGINAL. Do not edit.\n"
    "namespace TacSim\n{\n"
    "    public static class ArucoOriginal\n    {\n"
    "        public const int Size = 5;\n"
    "        // 25 bits per marker; bit 24 is the top-left data cell, row-major, 1 = white.\n"
    "        public static readonly uint[] Codes =\n        {\n"
    f"{rows}\n"
    "        };\n\n"
    "        public static bool IsWhite(int id, int row, int column) =>\n"
    "            ((Codes[id] >> (24 - (row * Size + column))) & 1) != 0;\n"
    "    }\n}\n",
    encoding="utf-8",
    newline="\n",
)
print(f"wrote {len(codes)} markers to {OUT}")
